[package]
name = "effers"
version = "0.1.0"
edition = "2021"

[workspace]
members = ["effers-derive"]

[dependencies]
effers-derive = { path = "./effers-derive" }

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "my_benchmark"
harness = false
